### ISSUE TITLE
Is preview feature supported?

### ISSUE THREAD

**Issue by Mister-Hope** [BeiyanYunyi/sodesu#2]
Official waline client supports markdown preview by bundling marked. However marked itself has about 20kb size under gzip, and core script of solids is > 7kb under gzip, so I think you are absolutely removing it. Also since I am not seeing any demos, I am not sure if there are other features which are removed either.

could you please add them in docs as well? Also you can make comparison with official client by listing features you added, features you removed and size reduced, that could be a lot better for users who does not care features you remove but want a lighter client.

**Comment by BeiyanYunyi** [comment]
> could you please add them in docs as well?

I'm going to do it.

**Comment by BeiyanYunyi** [comment]
https://beiyanyunyi.github.io/sodesu/trade-offs

Done.

**Comment by BeiyanYunyi** [comment]
> core script of solids is > 7kb under gzip

![图片](https://user-images.githubusercontent.com/14120445/217196875-78e97b35-e7db-44e6-a99b-ce4f682b991f.png)

Since most parts of solid.js are tree-shakeable, it will not as large as `bundlephobia.com` 's display. Including solid.js into bundle will only increase the bundle by ~5kB instead of 7kB.

The same thing happens on Vue.js too, since it's also tree-shakeable, `bundlephobia.com` can only give us a approximate data.
